#!/usr/bin/env bash
#Setting the Loadbalancer HAProxy & Frontend
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get install haproxy=1.7.\* -y
echo "frontend http_front
         bind *:80
         default_backend http_rear
      backend http_rear
         balance roundrobin
            server 20261-web-01 34.204.180.83:80 check
            server 20261-web-02 44.192.252.65:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
